import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import UserProfile from '@/components/UserProfile';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <div className='container p-4'>
            <div className='flex justify-between items-center mb-4'>
              <h1 className='text-1xl font-bold'>WELCOME TO NEXTJS</h1>
              <UserProfile />
            </div>
          </div>
          <div style={{ padding: 24 }}>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
